package view;



import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Automovel;
import model.dao.AutomovelDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));

        //readJTable();

    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        AutomovelDAO pdao = new AutomovelDAO();

        for (Automovel p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getPlaca(),
                p.getNome(),          
                p.getPreco(),
                p.getAno(),
                p.getModelo()
            });

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btCad = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cxModelo = new javax.swing.JTextField();
        cxPreco = new javax.swing.JTextField();
        cxAno = new javax.swing.JTextField();
        cxNome = new javax.swing.JTextField();
        cxPlaca = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Veiculos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        btCad.setBackground(new java.awt.Color(153, 153, 255));
        btCad.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-propriedade-64.png"))); // NOI18N
        btCad.setText("Cadastrar Automóvel");
        btCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadActionPerformed(evt);
            }
        });
        jPanel1.add(btCad);
        btCad.setBounds(260, 520, 450, 90);

        btLimpar.setBackground(new java.awt.Color(204, 255, 255));
        btLimpar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-limpar-formatação-50.png"))); // NOI18N
        btLimpar.setText(" Limpar Campos");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar);
        btLimpar.setBounds(490, 250, 530, 70);

        tabela.setAutoCreateRowSorter(true);
        tabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabela.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Nome", "Preco", "Ano", "Modelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setAlignmentX(2.5F);
        tabela.setAlignmentY(2.5F);
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabela.setFocusable(false);
        tabela.setGridColor(new java.awt.Color(0, 0, 0));
        tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
            tabela.getColumnModel().getColumn(4).setResizable(false);
        }
        tabela.getAccessibleContext().setAccessibleName("");
        tabela.getAccessibleContext().setAccessibleParent(tabela);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 330, 1000, 180);

        jButton2.setBackground(new java.awt.Color(51, 255, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-17387-0-73139-atualizar-esquerda-32-setas-50.png"))); // NOI18N
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton2KeyReleased(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(710, 520, 310, 90);

        jButton3.setBackground(new java.awt.Color(255, 51, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-apagar-para-sempre-64.png"))); // NOI18N
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 520, 240, 90);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-excluir-45.png"))); // NOI18N
        jButton1.setText("Desconectar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(790, 10, 230, 50);

        jLabel6.setBackground(new java.awt.Color(204, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 64)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8.png"))); // NOI18N
        jLabel6.setText(" Lista de Automóveis");
        jLabel6.setToolTipText("");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 0, 630, 70);

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-banco-de-dados-de-pesquisa-64.png"))); // NOI18N
        jButton4.setText("Buscar Dados");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 250, 470, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(690, 0, 80, 70);

        jPanel2.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Preco:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 70, 80, 30);

        jLabel7.setBackground(new java.awt.Color(153, 153, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("AnoFabri:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 100, 80, 30);

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Placa:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 80, 30);

        jLabel8.setBackground(new java.awt.Color(153, 153, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Modelo:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 130, 80, 30);

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 40, 80, 30);

        cxModelo.setBackground(new java.awt.Color(255, 255, 204));
        cxModelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxModelo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(cxModelo);
        cxModelo.setBounds(90, 130, 900, 30);

        cxPreco.setBackground(new java.awt.Color(255, 255, 204));
        cxPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxPreco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cxPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cxPrecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxPrecoFocusLost(evt);
            }
        });
        cxPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPrecoActionPerformed(evt);
            }
        });
        cxPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxPrecoKeyPressed(evt);
            }
        });
        jPanel2.add(cxPreco);
        cxPreco.setBounds(90, 70, 900, 30);

        cxAno.setBackground(new java.awt.Color(255, 255, 204));
        cxAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxAno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxAnoActionPerformed(evt);
            }
        });
        jPanel2.add(cxAno);
        cxAno.setBounds(90, 100, 900, 30);

        cxNome.setBackground(new java.awt.Color(255, 255, 204));
        cxNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxNome.setToolTipText("");
        cxNome.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cxNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cxNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxNomeFocusLost(evt);
            }
        });
        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });
        cxNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxNomeKeyPressed(evt);
            }
        });
        jPanel2.add(cxNome);
        cxNome.setBounds(90, 40, 900, 30);

        cxPlaca.setBackground(new java.awt.Color(255, 255, 204));
        cxPlaca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxPlaca.setToolTipText("");
        cxPlaca.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cxPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPlacaActionPerformed(evt);
            }
        });
        jPanel2.add(cxPlaca);
        cxPlaca.setBounds(90, 10, 900, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 70, 1000, 170);

        jPanel3.setBackground(new java.awt.Color(51, 255, 51));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 330, 1000, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1040, 630);

        setSize(new java.awt.Dimension(1077, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Deseja Sair E Desconectar?", null, JOptionPane.YES_NO_OPTION);
  
        if (x == 0) {
            JOptionPane.showMessageDialog(null,"Banco Desconectado com Sucesso");
            System.exit(0);
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        cxPlaca.setText("");
        cxNome.setText("");
        cxAno.setText("");
        cxPreco.setText("");
        cxModelo.setText("");
        JOptionPane.showMessageDialog(null,"Campos limpos");
    }//GEN-LAST:event_btLimparActionPerformed

    private void cxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxAnoActionPerformed

    private void btCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadActionPerformed
        Automovel p = new Automovel();
        AutomovelDAO dao = new AutomovelDAO();
 
        p.setPlaca(cxPlaca.getText());
        p.setNome(cxNome.getText());
        p.setAno(cxAno.getText());
        p.setPreco(cxPreco.getText());
        p.setModelo(cxModelo.getText());
        
        if(cxPlaca.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Placa Esta em Branco!");
        }
        else{
            dao.create(p);
            readJTable();
            
            cxPlaca.setText("");
            cxNome.setText("");
            cxAno.setText("");
            cxPreco.setText("");
            cxModelo.setText("");
        }
    }//GEN-LAST:event_btCadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(tabela.getSelectedRow() != -1){
        Automovel p = new Automovel();
        AutomovelDAO dao = new AutomovelDAO();
          
        p.setNome(cxNome.getText());
        p.setAno(cxAno.getText());
        p.setPreco(cxPreco.getText());
        p.setModelo(cxModelo.getText());
        p.setPlaca((String) tabela.getValueAt(tabela.getSelectedRow(), 0));
        dao.update(p);

        readJTable();

        }else {
           JOptionPane.showMessageDialog(null, "Selecione um Automovel para Atualizar!");
       }
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyReleased
    }//GEN-LAST:event_jButton2KeyReleased

    private void tabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaKeyReleased
        if (tabela.getSelectedRow() != -1) {
            cxPlaca.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            cxNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            cxPreco.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            cxAno.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            cxModelo.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_tabelaKeyReleased

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if (tabela.getSelectedRow() != -1) {
            cxPlaca.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            cxNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            cxPreco.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            cxAno.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            cxModelo.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(tabela.getSelectedRow() != -1){
         Automovel p = new Automovel();
         AutomovelDAO dao = new AutomovelDAO();

         p.setPlaca((String) tabela.getValueAt(tabela.getSelectedRow(), 0));
         dao.delete(p);

         readJTable();

        }else {
           JOptionPane.showMessageDialog(null, "Selecione um Automovel para Excluir!");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        AutomovelDAO pdao = new AutomovelDAO();

        for (Automovel p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getPlaca(),
                p.getNome(),          
                p.getPreco(),
                p.getAno(),
                p.getModelo()
            });

        }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cxPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPlacaActionPerformed

    }//GEN-LAST:event_cxPlacaActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed

    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxNomeFocusGained

    }//GEN-LAST:event_cxNomeFocusGained

    private void cxNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxNomeFocusLost

    }//GEN-LAST:event_cxNomeFocusLost

    private void cxNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNomeKeyPressed

    }//GEN-LAST:event_cxNomeKeyPressed

    private void cxPrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxPrecoFocusGained


    }//GEN-LAST:event_cxPrecoFocusGained

    private void cxPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxPrecoFocusLost


    }//GEN-LAST:event_cxPrecoFocusLost

    private void cxPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxPrecoKeyPressed

    }//GEN-LAST:event_cxPrecoKeyPressed

    private void cxPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCad;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField cxAno;
    private javax.swing.JTextField cxModelo;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPlaca;
    private javax.swing.JTextField cxPreco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}